postMessage({awards:{
	"kaitlyn":{
		"groupchat":true,
		"community":true,
		"halloween2012":true
	},
	"wbarton":{
		"community":true
		"TriviaKnight":true
	},
	"rinarin":{
		"groupchat":true,
		"community":true,
		"halloween2012":true,
		"TriviaKnight":true
	},
	"raiden":{
		"groupchat":true,
		"community":true
	},
	"crossbourne":{
		"groupchat":true,
		"community":true,
		"TriviaKnight":true
	},
	"thejadefalcon":{
		"groupchat":true,
		"community":true,
		"TriviaKnight":true
	},
	"lokonopa":{
		"groupchat":true,
		"community":true
	},
	"cult":{
		"groupchat":true,
		"community":true
	},
	"cg":{
		"groupchat":true,
		"community":true,
		"halloween2012":true
	},
	"chronicdiscord":{
		"groupchat":true,
		"TriviaKnight":true
	},
	"c00lizz":{
		"groupchat":true
	},
	"shadow0524":{
		"groupchat":true
	},
	"bufetman":{
		"groupchat":true
	},
	"hardekak":{
		"groupchat":true
	},
	"kappei":{
		"groupchat":true
	},
	"dimon222":{
		"groupchat":true
	},
	"beaar":{
		"groupchat":true
	},
	"torian":{
		"groupchat":true
	},
	"ppg113":{
		"groupchat":true
	},
	"tr4656":{
		"groupchat":true,
		"TriviaKnight":true
	},
	"kelfryn":{
		"groupchat":true
	},
	"generalchaos":{
		"groupchat":true
	},
	"corvo":{
		"groupchat":true
	},
	"nosef":{
		"groupchat":true
	},
	"mrcastiglia":{
		"groupchat":true,
		"TriviaKnight":true
	},
	"dm789":{
		"groupchat":true
	},
	"efreak":{
		"groupchat":true
	},
	"killerlotus":{
		"groupchat":true
	},
	"bobofatt":{
		"groupchat":true,
		"TriviaKnight":true
	},
	"trinityglasfille":{
		"groupchat":true
	},
	"vegetabol":{
		"groupchat":true
	},
	"mezza":{
		"groupchat":true,
		"TriviaKnight":true
	},
	"atomicwoodchuck":{
		"community":true
	},
	"zo":{
		"community":true
	},
	"tragikos":{
		"community":true
	},
	"calimero100582":{
		"halloween2012":true
	},
	"armorking63":{
		"halloween2012":true
	},
	"kalekip1":{
		"halloween2012":true
	},
	"thegrinder":{
		"halloween2012":true
	},
	"wheatley5981":{
		"halloween2012":true
	},
	"xiangming":{
		"halloween2012":true
	},
	"btgz":{
		"halloween2012":true
	},
	"dbg":{
		"halloween2012":true
	},
	"pe99":{
		"halloween2012":true
	},
	"beale":{
		"halloween2012":true
	},
	"getmyass15":{
		"halloween2012":true
	},
	"dragonbob":{
		"halloween2012":true
	},
	"andrea":{
		"halloween2012":true
	},
	"whiteguy3":{
		"halloween2012":true
	},
	"skanda":{
		"halloween2012":true
	},
	"bestduck":{
		"halloween2012":true
	},
	"jamoke":{
		"halloween2012":true
	},
	"zerocoolzc":{
		"halloween2012":true
	},
	"tristetea":{
		"halloween2012":true
	},
	"spderkiss":{
		"halloween2012":true
	},
	"hotroom":{
		"halloween2012":true
	},
	"arnab21":{
		"halloween2012":true,
		"groupchat": true
	},
	"nfreak":{
		"halloween2012":true
	},
	"renegado447":{
		"halloween2012":true
	},
	"croman":{
		"halloween2012":true
	},
	"toloko":{
		"halloween2012":true
	},
	"khairan":{
		"halloween2012":true
	},
	"frozened":{
		"halloween2012":true
	},
	"tickker":{
		"halloween2012":true
	},
	"marakuja":{
		"halloween2012":true
	},
	"pruflas":{
		"halloween2012":true
	},
	"zelos":{
		"halloween2012":true
	},
	"xiangming":{
		"halloween2012":true
	},
	"mikecraz":{
		"halloween2012":true
	},
	"harvey":{
		"halloween2012":true
	},
	"xdanx":{
		"halloween2012":true
	},
	"kryptonite":{
		"halloween2012":true
	},
	"truie":{
		"halloween2012":true
	},
	"jason369":{
		"halloween2012":true
	},
	"matejmoo":{
		"halloween2012":true
	},
	"rsmonster":{
		"halloween2012":true
	},
	"lezz":{
		"halloween2012":true
	},
	"kamatsu01":{
		"halloween2012":true
	},
	"lezz":{
		"halloween2012":true
	},
	"overiderjustino":{
		"halloween2012":true
	},
	"ninjacrow":{
		"halloween2012":true
	},
	"vyruz22":{
		"halloween2012":true
	},
	"tutackhamen":{
		"halloween2012":true
	},
	"glennfrank":{
		"halloween2012":true
	},
	"goodgorilla":{
		"halloween2012":true
	},
	"bernardoone":{
		"halloween2012":true
	},
	"derangedboar":{
		"groupchat":true,
		"halloween2012":true
	},
	"lucasc":{
		"halloween2012":true
	},
	"gatsby":{
		"halloween2012":true
	},
	"botev1912":{
		"halloween2012":true
	},
	"abub":{
		"halloween2012":true
	},
	"reis3031":{
		"halloween2012":true
	},
	"abstractchaos":{
		"halloween2012":true
	},
	"wartinald":{
		"halloween2012":true
	},
	"zlia":{
		"halloween2012":true
	},
	"korki":{
		"halloween2012":true
	},
	"paulstar":{
		"halloween2012":true
	},
	"puersushi":{
		"halloween2012":true
	},
	"snake994":{
		"halloween2012":true
	},
	"adzz":{
		"halloween2012":true
	},
	"cityheadache":{
		"halloween2012":true
	},
	"hackerkok":{
		"halloween2012":true
	},
	"serokh":{
		"halloween2012":true
	},
	"bugio":{
		"halloween2012":true
	},
	"srm28":{
		"halloween2012":true
	},
	"whyren":{
		"halloween2012":true
	},
	"frylynkz":{
		"halloween2012":true
	},
	"reaperlinkz":{
		"halloween2012":true
	},
	"lacknock":{
		"halloween2012":true
	},
	"agito":{
		"halloween2012":true
	},
	"revoshift":{
		"halloween2012":true
	},
	"lemavik":{
		"halloween2012":true
	},
	"chimperilur":{
		"halloween2012":true
	},
	"tdotn":{
		"halloween2012":true
	},
	"trakk":{
		"halloween2012":true
	},
	"ronik":{
		"halloween2012":true
	},
	"motorkar":{
		"halloween2012":true
	},
	"d3struction":{
		"halloween2012":true
	},
	"zuxicovp":{
		"halloween2012":true
	},
	"lorkhan":{
		"halloween2012":true
	},
	"wojtek858":{
		"halloween2012":true
	},
	"kotkas44":{
		"halloween2012":true
	},
	"hnnngh":{
		"halloween2012":true,
		"TriviaKnight":true
	},
	"shazbot":{
		"halloween2012":true
	},
	"lunk":{
		"halloween2012":true
	},
	"thomppetty":{
		"halloween2012":true
	},
	"sepang":{
		"halloween2012":true
	},
	"evilmoo":{
		"halloween2012":true
	},
	"eisenzange":{
		"halloween2012":true
	},
	"backslashn":{
		"halloween2012":true
	},
	"andrestv":{
		"halloween2012":true
	},
	"kaoticz":{
		"halloween2012":true
	},
	"parasen":{
		"halloween2012":true
	},
	"caerbannog":{
		"halloween2012":true,
		"TriviaKnight":true
	},
	"shiropt":{
		"halloween2012":true
	},
	"evilzor":{
		"halloween2012":true
	},
	"ceildric":{
		"halloween2012":true
	},
	"dietblood":{
		"halloween2012":true
	},
	"marcaobr":{
		"halloween2012":true
	},
	"locien":{
		"halloween2012":true
	},
	"kaisertroll":{
		"halloween2012":true
	},
	"sherardy":{
		"halloween2012":true
	},
	"fenrakk101":{
		"halloween2012":true
	},
	"kurgan":{
		"halloween2012":true,
		"TriviaKnight":true
	},
	"firstfearer":{
		"halloween2012":true
	},
	"joaquin95":{
		"halloween2012":true
	},
	"xsun":{
		"halloween2012":true
	},
	"pash1k":{
		"halloween2012":true
	},
	"godamage":{
		"halloween2012":true
	},
	"wolfviking":{
		"halloween2012":true
	},
	"zomby2d":{
		"halloween2012":true
	},
	"cubundara":{
		"halloween2012":true
	},
	"zedingo":{
		"halloween2012":true
	},
	"yorimitsu":{
		"halloween2012":true
	},
	"evodoc":{
		"halloween2012":true
	},
	"jctango":{
		"halloween2012":true
	},
	"ptg":{
		"halloween2012":true,
		"groupchat":true
	},
	"trainn":{
		"halloween2012":true
	},
	"janrok":{
		"halloween2012":true
	},
	"ajdandy":{
		"halloween2012":true
	},
	"d3zik":{
		"halloween2012":true
	},
	"psygineer":{
		"halloween2012":true
	},
	"crille424":{
		"halloween2012":true
	},
	"celdiruen":{
		"halloween2012":true,
		"TriviaKnight":true
	},
	"effort":{
		"halloween2012":true
	},
	"semijames":{
		"halloween2012":true
	},
	"ball00n":{
		"halloween2012":true
	},
	"twiz":{
		"halloween2012":true
	},
	"zhur":{
		"halloween2012":true
	},
	"ageofarmageddon":{
		"halloween2012":true
	},
	"cmsn1991":{
		"halloween2012":true
	},
	"obscurin":{
		"halloween2012":true
	},
	"kwik":{
		"halloween2012":true
	},
	"deumas":{
		"halloween2012":true
	},
	"frixon33":{
		"halloween2012":true
	},
	"angel9rakoucobra":{
		"halloween2012":true
	},
	"b521":{
		"halloween2012":true
	},
	"screamy":{
		"halloween2012":true
	},
	"10uronly":{
		"halloween2012":true
	},
	"nickyiv":{
		"halloween2012":true
	},
	"yokuo":{
		"halloween2012":true
	},
	"nimbulan":{
		"halloween2012":true,
		"groupchat": true,
		"TriviaKnight":true
	},
	"mfromm":{
		"halloween2012":true
	},
	"leeka":{
		"halloween2012":true
	},
	"killergp123":{
		"halloween2012":true
	},
	"monukai":{
		"halloween2012":true,
		"TriviaKnight":true
	},
	"madnessnewb":{
		"groupchat":true,
		"halloween2012":true
	},
	"nikolai":{
		"halloween2012":true
	},
	"stuntkid87":{
		"halloween2012":true
	},
	"lajtning":{
		"halloween2012":true
	},
	"alphabets":{
		"halloween2012":true
	},
	"jeyko":{
		"halloween2012":true
	},
	"ramesrock":{
		"halloween2012":true
	},
	"crossx":{
		"halloween2012":true
	},
	"megagiga34":{
		"halloween2012":true,
		"groupchat":true
	},
	"rankor":{
		"halloween2012":true
	},
	"volf":{
		"halloween2012":true
	},
	"ansatsunin":{
		"halloween2012":true
	},
	"thepsykoking":{
		"halloween2012":true
	},
	"onboard":{
		"halloween2012":true
	},
	"krossx":{
		"halloween2012":true
	},
	"theponz":{
		"halloween2012":true
	},
	"gptrixie":{
		"halloween2012":true,
		"TriviaKnight":true
	},
	"huntingnoob":{
		"halloween2012":true
	},
	"intraining":{
		"halloween2012":true
	},
	"bubbybobble":{
		"halloween2012":true
	},
	"lrdx":{
		"halloween2012":true
	},
	"doritos2220":{
		"halloween2012":true
	},
	"ironsyt":{
		"halloween2012":true
	},
	"xdem":{
		"halloween2012":true
	},
	"dragon18":{
		"halloween2012":true
	},
	"l1nu5":{
		"halloween2012":true
	},
	"sentox":{
		"halloween2012":true
	},
	"szekesi":{
		"halloween2012":true
	},
	"tobiwan":{
		"halloween2012":true
	},
	"gh0st233":{
		"halloween2012":true
	},
	"tigerpup":{
		"halloween2012":true
	},
	"moody12":{
		"halloween2012":true
	},
	"texasic":{
		"halloween2012":true
	},
	"martin005":{
		"halloween2012":true
	},
	"bloodyro":{
		"halloween2012":true
	},
	"rotikering":{
		"halloween2012":true
	},
	"merolac":{
		"halloween2012":true
	},
	"ll":{
		"halloween2012":true
	},
	"megazet":{
		"halloween2012":true
	},
	"nick1337":{
		"halloween2012":true
	},
	"mtic":{
		"halloween2012":true
	},
	"ca3d0":{
		"halloween2012":true
	},
	"ssdd":{
		"halloween2012":true
	},
	"scellow":{
		"halloween2012":true
	},
	"dasgluk":{
		"halloween2012":true
	},
	"plebbles":{
		"halloween2012":true
	},
	"tuttu":{
		"halloween2012":true
	},
	"holo":{
		"halloween2012":true
	},
	"pangalaktichki":{
		"halloween2012":true
	},
	"torcidaverde":{
		"halloween2012":true
	},
	"killrclown":{
		"halloween2012":true
	},
	"psygineer":{
		"halloween2012":true
	},
	"wuut":{
		"halloween2012":true
	},
	"000knight":{
		"halloween2012":true
	},
	"nd1razor":{
		"halloween2012":true
	},
	"imatrix7":{
		"halloween2012":true
	},
	"easyczt":{
		"halloween2012":true
	},
	"ruddyadam":{
		"halloween2012":true
	},
	"crackerbear":{
		"halloween2012":true
	},
	"nonos":{
		"halloween2012":true
	},
	"jossarien":{
		"halloween2012":true
	},
	"irwinner":{
		"halloween2012":true
	},
	"relaxtea":{
		"halloween2012":true
	},
	"gumer15":{
		"halloween2012":true
	},
	"sklurm":{
		"halloween2012":true
	},
	"gaycowboy":{
		"halloween2012":true
	},
	"starscre4m":{
		"halloween2012":true
	},
	"syncz":{
		"halloween2012":true
	},
	"bambobob":{
		"halloween2012":true
	},
	"fragger":{
		"halloween2012":true
	},
	"theshobo":{
		"groupchat":true,
		"community":true,
		"halloween2012":true,
		"TriviaKnight":true
	},
	"l0cutus81":{
		"halloween2012":true
	},
	"xfallenangel":{
		"halloween2012":true
	},
	"ghostracer":{
		"halloween2012":true
	},
	"xcutofu":{
		"halloween2012":true
	},
	"thorwaechter":{
		"halloween2012":true
	},
	"faj":{
		"halloween2012":true
	},
	"glotzeulor":{
		"halloween2012":true
	},
	"explorerbc":{
		"halloween2012":true
	},
	"hymie8":{
		"halloween2012":true
	},
	"5tryker":{
		"halloween2012":true
	},
	"skumfidus":{
		"halloween2012":true
	},
	"a1amit":{
		"halloween2012":true
	},
	"ariadourden":{
		"halloween2012":true
	},
	"cn47":{
		"halloween2012":true
	},
	"cruelkot":{
		"halloween2012":true
	},
	"doc1":{
		"halloween2012":true,
		"groupchat":true
	},
	"newt182":{
		"halloween2012":true
	},
	"brutodetestssb":{
		"halloween2012":true
	},
	"dealerpl":{
		"halloween2012":true
	},
	"vydany":{
		"halloween2012":true
	},
	"elcor":{
		"halloween2012":true
	},
	"lienzo":{
		"halloween2012":true
	},
	"severus135":{
		"halloween2012":true
	},
	"delorian":{
		"halloween2012":true
	},
	"wyl9":{
		"halloween2012":true
	},
	"kenancatic97":{
		"halloween2012":true
	},
	"alisama":{
		"halloween2012":true
	},
	"voodoofox":{
		"halloween2012":true
	},
	"rosebuster":{
		"halloween2012":true
	},
	"ahoym8":{
		"halloween2012":true
	},
	"benschtrim":{
		"halloween2012":true
	},
	"acjencis":{
		"halloween2012":true
	},
	"dotazured":{
		"groupchat":true,
		"halloween2012":true,
		"halloween2013":true
	},
	"gawaine":{
		"halloween2012":true
	},
	"ana3mic":{
		"halloween2012":true
	},
	"golgalad":{
		"halloween2012":true
	},
	"flyingshoppingcart":{
		"halloween2012":true
	},
	"wilkuftw":{
		"halloween2012":true
	},
	"tibek":{
		"halloween2012":true
	},
	"kagatoasuka89":{
		"halloween2012":true
	},
	"redjevel":{
		"halloween2012":true
	},
	"xero8p":{
		"halloween2012":true
	},
	"corrupted":{
		"halloween2012":true
	},
	"lashatatu":{
		"halloween2012":true
	},
	"5474iv":{
		"halloween2012":true
	},
	"tutreach":{
		"halloween2012":true
	},
	"firedancer":{
		"halloween2012":true
	},
	"memoir":{
		"halloween2012":true
	},
	"creambanana":{
		"groupchat":true
	},
	"compassnorth":{
		"groupchat":true
	},
	"le4slie":{
		"groupchat":true
	},
	"infectedvein":{
		"groupchat":true
	},
	"thechack":{
		"groupchat":true
	},
	"mecorx":{
		"groupchat":true
	},
	"emotionengine":{
		"groupchat":true
	},
	"cxiong93":{
		"groupchat":true,
		"TriviaKnight":true
	},
	"unicorn":{
		"groupchat":true
	},
	"emily92x":{
		"groupchat":true
	},
	"way2tired":{
		"groupchat":true
	},
	"doubledragon666":{
		"TriviaKnight":true
	},
	"morphinebear":{
		"TriviaKnight":true
	},
	"deiru":{
		"groupchat":true,
		"TriviaKnight":true
	},
	"thegreenfairy":{
		"TriviaKnight":true
	},
	"thomen":{
		"TriviaKnight":true
	},
	"gainja":{
		"TriviaKnight":true
	},
	"kellhus":{
		"TriviaKnight":true
	},
	"richie":{
		"TriviaKnight":true
	},
	"gojays2025":{
		"groupchat":true,
		"TriviaKnight":true
	},
	"crazedanimal":{
		"groupchat":true,
		"TriviaKnight":true
	},
	"kokosabre":{
		"groupchat":true
	},
	"qetc":{
		"TriviaKnight":true
	},
	"truncat":{
		"TriviaKnight":true
	},
	"sparklepop":{
		"TriviaKnight":true
	},
	"aly":{
		"TriviaKnight":true
	},
	"bibboorton":{
		"TriviaKnight":true
	},
	"minibaa":{
		"TriviaKnight":true
	},
	"mostlyghostly":{
		"TriviaKnight":true
	},
	"koldwar":{
		"TriviaKnight":true
	},
	"irobbot":{
		"TriviaKnight":true
	},
	"mrmonotone":{
		"TriviaKnight":true
	},
	"dartel":{
		"TriviaKnight":true
	},
	"dardreigraves":{
		"TriviaKnight":true
	},
	"rannos":{
		"TriviaKnight":true
	},
	"meluvia":{
		"TriviaKnight":true
	},
	"acorpse":{
		"groupchat":true,
		"TriviaKnight":true
	},
	"leomoty":{
		"TriviaKnight":true
	},
	"fortybucksdown":{
		"TriviaKnight":true
	},
	"nevyn":{
		"TriviaKnight":true
	},
	"andreavus":{
		"TriviaKnight":true
	},
	"jazzman0":{
		"TriviaKnight":true
	},
	"wargharbl":{
		"TriviaKnight":true
	},
	"peasofcrab":{
		"TriviaKnight":true
	},
	"deltabrainwave":{
		"TriviaKnight":true
	},
	"wormy":{
		"TriviaKnight":true
	},
	"psychockey":{
		"TriviaKnight":true
	},
	"taytothief":{
		"TriviaKnight":true
	},
	"lethalabsol":{
		"TriviaKnight":true
	},
	"sexyfelga":{
		"TriviaKnight":true
	},
	"grundig":{
		"TriviaKnight":true
	},
	"omnitau":{
		"TriviaKnight":true
	},
	"bobertmann":{
		"TriviaKnight":true
	},
	"doobs":{
		"TriviaKnight":true
	},
	"omer681":{
		"TriviaKnight":true
	},
	"oracle104":{
		"TriviaKnight":true
	},
	"doctorofjournalism":{
		"TriviaKnight":true
	},
	"junable":{
		"TriviaKnight":true
	},
	"analfries":{
		"TriviaKnight":true
	},
	"fedttony":{
		"TriviaKnight":true
	},
	"4evra":{
		"TriviaKnight":true
	},
	"likwitsnake":{
		"TriviaKnight":true
	},
	"elix":{
		"TriviaKnight":true
	},
	"nastyhero":{
		"TriviaKnight":true
	},
	"dillonmabry":{
		"TriviaKnight":true
	},
	"seagull7":{
		"TriviaKnight":true
	},
	"cth":{
		"TriviaKnight":true
	},
	"regifterer":{
		"TriviaKnight":true
	},
	"kerepekman":{
		"TriviaKnight":true
	},
	"killa24":{
		"TriviaKnight":true
	},
	"spaghadeity":{
		"TriviaKnight":true
	},
	"notnsane":{
		"TriviaKnight":true
	}
	
}},'*')